#ifndef CANOLA_AXI_SLAVE_H
#define CANOLA_AXI_SLAVE_H

#define CANOLA_AXI_SLAVE_BASEADDR 0x0

/* Register: STATUS */
#define STATUS_OFFSET 0x0
#define STATUS_RESET 0x0

/* Field: RX_MSG_VALID */
#define STATUS_RX_MSG_VALID_OFFSET 0
#define STATUS_RX_MSG_VALID_WIDTH 1
#define STATUS_RX_MSG_VALID_RESET 0x0
#define STATUS_RX_MSG_VALID_MASK 0x1

/* Field: TX_BUSY */
#define STATUS_TX_BUSY_OFFSET 1
#define STATUS_TX_BUSY_WIDTH 1
#define STATUS_TX_BUSY_RESET 0x0
#define STATUS_TX_BUSY_MASK 0x2

/* Field: TX_DONE */
#define STATUS_TX_DONE_OFFSET 2
#define STATUS_TX_DONE_WIDTH 1
#define STATUS_TX_DONE_RESET 0x0
#define STATUS_TX_DONE_MASK 0x4

/* Field: TX_FAILED */
#define STATUS_TX_FAILED_OFFSET 3
#define STATUS_TX_FAILED_WIDTH 1
#define STATUS_TX_FAILED_RESET 0x0
#define STATUS_TX_FAILED_MASK 0x8

/* Field: ERROR_STATE */
#define STATUS_ERROR_STATE_OFFSET 4
#define STATUS_ERROR_STATE_WIDTH 2
#define STATUS_ERROR_STATE_RESET 0x0
#define STATUS_ERROR_STATE_MASK 0x30

/* Register: CONTROL */
#define CONTROL_OFFSET 0x4
#define CONTROL_RESET 0x0

/* Field: TX_START */
#define CONTROL_TX_START_OFFSET 0
#define CONTROL_TX_START_WIDTH 1
#define CONTROL_TX_START_RESET 0x0
#define CONTROL_TX_START_MASK 0x1

/* Field: RESET_TX_MSG_SENT_COUNTER */
#define CONTROL_RESET_TX_MSG_SENT_COUNTER_OFFSET 1
#define CONTROL_RESET_TX_MSG_SENT_COUNTER_WIDTH 1
#define CONTROL_RESET_TX_MSG_SENT_COUNTER_RESET 0x0
#define CONTROL_RESET_TX_MSG_SENT_COUNTER_MASK 0x2

/* Field: RESET_TX_FAILED_COUNTER */
#define CONTROL_RESET_TX_FAILED_COUNTER_OFFSET 2
#define CONTROL_RESET_TX_FAILED_COUNTER_WIDTH 1
#define CONTROL_RESET_TX_FAILED_COUNTER_RESET 0x0
#define CONTROL_RESET_TX_FAILED_COUNTER_MASK 0x4

/* Field: RESET_TX_ACK_ERROR_COUNTER */
#define CONTROL_RESET_TX_ACK_ERROR_COUNTER_OFFSET 3
#define CONTROL_RESET_TX_ACK_ERROR_COUNTER_WIDTH 1
#define CONTROL_RESET_TX_ACK_ERROR_COUNTER_RESET 0x0
#define CONTROL_RESET_TX_ACK_ERROR_COUNTER_MASK 0x8

/* Field: RESET_TX_ARB_LOST_COUNTER */
#define CONTROL_RESET_TX_ARB_LOST_COUNTER_OFFSET 4
#define CONTROL_RESET_TX_ARB_LOST_COUNTER_WIDTH 1
#define CONTROL_RESET_TX_ARB_LOST_COUNTER_RESET 0x0
#define CONTROL_RESET_TX_ARB_LOST_COUNTER_MASK 0x10

/* Field: RESET_TX_BIT_ERROR_COUNTER */
#define CONTROL_RESET_TX_BIT_ERROR_COUNTER_OFFSET 5
#define CONTROL_RESET_TX_BIT_ERROR_COUNTER_WIDTH 1
#define CONTROL_RESET_TX_BIT_ERROR_COUNTER_RESET 0x0
#define CONTROL_RESET_TX_BIT_ERROR_COUNTER_MASK 0x20

/* Field: RESET_TX_RETRANSMIT_COUNTER */
#define CONTROL_RESET_TX_RETRANSMIT_COUNTER_OFFSET 6
#define CONTROL_RESET_TX_RETRANSMIT_COUNTER_WIDTH 1
#define CONTROL_RESET_TX_RETRANSMIT_COUNTER_RESET 0x0
#define CONTROL_RESET_TX_RETRANSMIT_COUNTER_MASK 0x40

/* Field: RESET_RX_MSG_RECV_COUNTER */
#define CONTROL_RESET_RX_MSG_RECV_COUNTER_OFFSET 7
#define CONTROL_RESET_RX_MSG_RECV_COUNTER_WIDTH 1
#define CONTROL_RESET_RX_MSG_RECV_COUNTER_RESET 0x0
#define CONTROL_RESET_RX_MSG_RECV_COUNTER_MASK 0x80

/* Field: RESET_RX_CRC_ERROR_COUNTER */
#define CONTROL_RESET_RX_CRC_ERROR_COUNTER_OFFSET 8
#define CONTROL_RESET_RX_CRC_ERROR_COUNTER_WIDTH 1
#define CONTROL_RESET_RX_CRC_ERROR_COUNTER_RESET 0x0
#define CONTROL_RESET_RX_CRC_ERROR_COUNTER_MASK 0x100

/* Field: RESET_RX_FORM_ERROR_COUNTER */
#define CONTROL_RESET_RX_FORM_ERROR_COUNTER_OFFSET 9
#define CONTROL_RESET_RX_FORM_ERROR_COUNTER_WIDTH 1
#define CONTROL_RESET_RX_FORM_ERROR_COUNTER_RESET 0x0
#define CONTROL_RESET_RX_FORM_ERROR_COUNTER_MASK 0x200

/* Field: RESET_RX_STUFF_ERROR_COUNTER */
#define CONTROL_RESET_RX_STUFF_ERROR_COUNTER_OFFSET 10
#define CONTROL_RESET_RX_STUFF_ERROR_COUNTER_WIDTH 1
#define CONTROL_RESET_RX_STUFF_ERROR_COUNTER_RESET 0x0
#define CONTROL_RESET_RX_STUFF_ERROR_COUNTER_MASK 0x400

/* Register: CONFIG */
#define CONFIG_OFFSET 0x8
#define CONFIG_RESET 0x0

/* Field: TX_RETRANSMIT_EN */
#define CONFIG_TX_RETRANSMIT_EN_OFFSET 0
#define CONFIG_TX_RETRANSMIT_EN_WIDTH 1
#define CONFIG_TX_RETRANSMIT_EN_RESET 0x0
#define CONFIG_TX_RETRANSMIT_EN_MASK 0x1

/* Field: BTL_TRIPLE_SAMPLING_EN */
#define CONFIG_BTL_TRIPLE_SAMPLING_EN_OFFSET 1
#define CONFIG_BTL_TRIPLE_SAMPLING_EN_WIDTH 1
#define CONFIG_BTL_TRIPLE_SAMPLING_EN_RESET 0x0
#define CONFIG_BTL_TRIPLE_SAMPLING_EN_MASK 0x2

/* Register: BTL_PROP_SEG */
#define BTL_PROP_SEG_OFFSET 0x20
#define BTL_PROP_SEG_RESET 0x7

/* Register: BTL_PHASE_SEG1 */
#define BTL_PHASE_SEG1_OFFSET 0x24
#define BTL_PHASE_SEG1_RESET 0x7

/* Register: BTL_PHASE_SEG2 */
#define BTL_PHASE_SEG2_OFFSET 0x28
#define BTL_PHASE_SEG2_RESET 0x7

/* Register: BTL_SYNC_JUMP_WIDTH */
#define BTL_SYNC_JUMP_WIDTH_OFFSET 0x2c
#define BTL_SYNC_JUMP_WIDTH_RESET 0x1

/* Register: TIME_QUANTA_CLOCK_SCALE */
#define TIME_QUANTA_CLOCK_SCALE_OFFSET 0x30
#define TIME_QUANTA_CLOCK_SCALE_RESET 0xF

/* Register: TRANSMIT_ERROR_COUNT */
#define TRANSMIT_ERROR_COUNT_OFFSET 0x34
#define TRANSMIT_ERROR_COUNT_RESET 0x0

/* Register: RECEIVE_ERROR_COUNT */
#define RECEIVE_ERROR_COUNT_OFFSET 0x38
#define RECEIVE_ERROR_COUNT_RESET 0x0

/* Register: TX_MSG_SENT_COUNT */
#define TX_MSG_SENT_COUNT_OFFSET 0x3c
#define TX_MSG_SENT_COUNT_RESET 0x0

/* Register: TX_FAILED_COUNT */
#define TX_FAILED_COUNT_OFFSET 0x40
#define TX_FAILED_COUNT_RESET 0x0

/* Register: TX_ACK_ERROR_COUNT */
#define TX_ACK_ERROR_COUNT_OFFSET 0x44
#define TX_ACK_ERROR_COUNT_RESET 0x0

/* Register: TX_ARB_LOST_COUNT */
#define TX_ARB_LOST_COUNT_OFFSET 0x48
#define TX_ARB_LOST_COUNT_RESET 0x0

/* Register: TX_BIT_ERROR_COUNT */
#define TX_BIT_ERROR_COUNT_OFFSET 0x4c
#define TX_BIT_ERROR_COUNT_RESET 0x0

/* Register: TX_RETRANSMIT_COUNT */
#define TX_RETRANSMIT_COUNT_OFFSET 0x50
#define TX_RETRANSMIT_COUNT_RESET 0x0

/* Register: RX_MSG_RECV_COUNT */
#define RX_MSG_RECV_COUNT_OFFSET 0x54
#define RX_MSG_RECV_COUNT_RESET 0x0

/* Register: RX_CRC_ERROR_COUNT */
#define RX_CRC_ERROR_COUNT_OFFSET 0x58
#define RX_CRC_ERROR_COUNT_RESET 0x0

/* Register: RX_FORM_ERROR_COUNT */
#define RX_FORM_ERROR_COUNT_OFFSET 0x5c
#define RX_FORM_ERROR_COUNT_RESET 0x0

/* Register: RX_STUFF_ERROR_COUNT */
#define RX_STUFF_ERROR_COUNT_OFFSET 0x60
#define RX_STUFF_ERROR_COUNT_RESET 0x0

/* Register: TX_MSG_ID */
#define TX_MSG_ID_OFFSET 0x64
#define TX_MSG_ID_RESET 0x0

/* Field: EXT_ID_EN */
#define TX_MSG_ID_EXT_ID_EN_OFFSET 0
#define TX_MSG_ID_EXT_ID_EN_WIDTH 1
#define TX_MSG_ID_EXT_ID_EN_RESET 0x0
#define TX_MSG_ID_EXT_ID_EN_MASK 0x1

/* Field: RTR_EN */
#define TX_MSG_ID_RTR_EN_OFFSET 1
#define TX_MSG_ID_RTR_EN_WIDTH 1
#define TX_MSG_ID_RTR_EN_RESET 0x0
#define TX_MSG_ID_RTR_EN_MASK 0x2

/* Field: ARB_ID_B */
#define TX_MSG_ID_ARB_ID_B_OFFSET 2
#define TX_MSG_ID_ARB_ID_B_WIDTH 18
#define TX_MSG_ID_ARB_ID_B_RESET 0x0
#define TX_MSG_ID_ARB_ID_B_MASK 0xffffc

/* Field: ARB_ID_A */
#define TX_MSG_ID_ARB_ID_A_OFFSET 20
#define TX_MSG_ID_ARB_ID_A_WIDTH 11
#define TX_MSG_ID_ARB_ID_A_RESET 0x0
#define TX_MSG_ID_ARB_ID_A_MASK 0x7ff00000

/* Register: TX_PAYLOAD_LENGTH */
#define TX_PAYLOAD_LENGTH_OFFSET 0x68
#define TX_PAYLOAD_LENGTH_RESET 0x0

/* Register: TX_PAYLOAD_0 */
#define TX_PAYLOAD_0_OFFSET 0x6c
#define TX_PAYLOAD_0_RESET 0x0

/* Field: PAYLOAD_BYTE_0 */
#define TX_PAYLOAD_0_PAYLOAD_BYTE_0_OFFSET 0
#define TX_PAYLOAD_0_PAYLOAD_BYTE_0_WIDTH 8
#define TX_PAYLOAD_0_PAYLOAD_BYTE_0_RESET 0x0
#define TX_PAYLOAD_0_PAYLOAD_BYTE_0_MASK 0xff

/* Field: PAYLOAD_BYTE_1 */
#define TX_PAYLOAD_0_PAYLOAD_BYTE_1_OFFSET 8
#define TX_PAYLOAD_0_PAYLOAD_BYTE_1_WIDTH 8
#define TX_PAYLOAD_0_PAYLOAD_BYTE_1_RESET 0x0
#define TX_PAYLOAD_0_PAYLOAD_BYTE_1_MASK 0xff00

/* Field: PAYLOAD_BYTE_2 */
#define TX_PAYLOAD_0_PAYLOAD_BYTE_2_OFFSET 16
#define TX_PAYLOAD_0_PAYLOAD_BYTE_2_WIDTH 8
#define TX_PAYLOAD_0_PAYLOAD_BYTE_2_RESET 0x0
#define TX_PAYLOAD_0_PAYLOAD_BYTE_2_MASK 0xff0000

/* Field: PAYLOAD_BYTE_3 */
#define TX_PAYLOAD_0_PAYLOAD_BYTE_3_OFFSET 24
#define TX_PAYLOAD_0_PAYLOAD_BYTE_3_WIDTH 8
#define TX_PAYLOAD_0_PAYLOAD_BYTE_3_RESET 0x0
#define TX_PAYLOAD_0_PAYLOAD_BYTE_3_MASK 0xff000000

/* Register: TX_PAYLOAD_1 */
#define TX_PAYLOAD_1_OFFSET 0x70
#define TX_PAYLOAD_1_RESET 0x0

/* Field: PAYLOAD_BYTE_4 */
#define TX_PAYLOAD_1_PAYLOAD_BYTE_4_OFFSET 0
#define TX_PAYLOAD_1_PAYLOAD_BYTE_4_WIDTH 8
#define TX_PAYLOAD_1_PAYLOAD_BYTE_4_RESET 0x0
#define TX_PAYLOAD_1_PAYLOAD_BYTE_4_MASK 0xff

/* Field: PAYLOAD_BYTE_5 */
#define TX_PAYLOAD_1_PAYLOAD_BYTE_5_OFFSET 8
#define TX_PAYLOAD_1_PAYLOAD_BYTE_5_WIDTH 8
#define TX_PAYLOAD_1_PAYLOAD_BYTE_5_RESET 0x0
#define TX_PAYLOAD_1_PAYLOAD_BYTE_5_MASK 0xff00

/* Field: PAYLOAD_BYTE_6 */
#define TX_PAYLOAD_1_PAYLOAD_BYTE_6_OFFSET 16
#define TX_PAYLOAD_1_PAYLOAD_BYTE_6_WIDTH 8
#define TX_PAYLOAD_1_PAYLOAD_BYTE_6_RESET 0x0
#define TX_PAYLOAD_1_PAYLOAD_BYTE_6_MASK 0xff0000

/* Field: PAYLOAD_BYTE_7 */
#define TX_PAYLOAD_1_PAYLOAD_BYTE_7_OFFSET 24
#define TX_PAYLOAD_1_PAYLOAD_BYTE_7_WIDTH 8
#define TX_PAYLOAD_1_PAYLOAD_BYTE_7_RESET 0x0
#define TX_PAYLOAD_1_PAYLOAD_BYTE_7_MASK 0xff000000

/* Register: RX_MSG_ID */
#define RX_MSG_ID_OFFSET 0x74
#define RX_MSG_ID_RESET 0x0

/* Field: EXT_ID_EN */
#define RX_MSG_ID_EXT_ID_EN_OFFSET 0
#define RX_MSG_ID_EXT_ID_EN_WIDTH 1
#define RX_MSG_ID_EXT_ID_EN_RESET 0x0
#define RX_MSG_ID_EXT_ID_EN_MASK 0x1

/* Field: RTR_EN */
#define RX_MSG_ID_RTR_EN_OFFSET 1
#define RX_MSG_ID_RTR_EN_WIDTH 1
#define RX_MSG_ID_RTR_EN_RESET 0x0
#define RX_MSG_ID_RTR_EN_MASK 0x2

/* Field: ARB_ID_B */
#define RX_MSG_ID_ARB_ID_B_OFFSET 2
#define RX_MSG_ID_ARB_ID_B_WIDTH 18
#define RX_MSG_ID_ARB_ID_B_RESET 0x0
#define RX_MSG_ID_ARB_ID_B_MASK 0xffffc

/* Field: ARB_ID_A */
#define RX_MSG_ID_ARB_ID_A_OFFSET 20
#define RX_MSG_ID_ARB_ID_A_WIDTH 11
#define RX_MSG_ID_ARB_ID_A_RESET 0x0
#define RX_MSG_ID_ARB_ID_A_MASK 0x7ff00000

/* Register: RX_PAYLOAD_LENGTH */
#define RX_PAYLOAD_LENGTH_OFFSET 0x78
#define RX_PAYLOAD_LENGTH_RESET 0x0

/* Register: RX_PAYLOAD_0 */
#define RX_PAYLOAD_0_OFFSET 0x7c
#define RX_PAYLOAD_0_RESET 0x0

/* Field: PAYLOAD_BYTE_0 */
#define RX_PAYLOAD_0_PAYLOAD_BYTE_0_OFFSET 0
#define RX_PAYLOAD_0_PAYLOAD_BYTE_0_WIDTH 8
#define RX_PAYLOAD_0_PAYLOAD_BYTE_0_RESET 0x0
#define RX_PAYLOAD_0_PAYLOAD_BYTE_0_MASK 0xff

/* Field: PAYLOAD_BYTE_1 */
#define RX_PAYLOAD_0_PAYLOAD_BYTE_1_OFFSET 8
#define RX_PAYLOAD_0_PAYLOAD_BYTE_1_WIDTH 8
#define RX_PAYLOAD_0_PAYLOAD_BYTE_1_RESET 0x0
#define RX_PAYLOAD_0_PAYLOAD_BYTE_1_MASK 0xff00

/* Field: PAYLOAD_BYTE_2 */
#define RX_PAYLOAD_0_PAYLOAD_BYTE_2_OFFSET 16
#define RX_PAYLOAD_0_PAYLOAD_BYTE_2_WIDTH 8
#define RX_PAYLOAD_0_PAYLOAD_BYTE_2_RESET 0x0
#define RX_PAYLOAD_0_PAYLOAD_BYTE_2_MASK 0xff0000

/* Field: PAYLOAD_BYTE_3 */
#define RX_PAYLOAD_0_PAYLOAD_BYTE_3_OFFSET 24
#define RX_PAYLOAD_0_PAYLOAD_BYTE_3_WIDTH 8
#define RX_PAYLOAD_0_PAYLOAD_BYTE_3_RESET 0x0
#define RX_PAYLOAD_0_PAYLOAD_BYTE_3_MASK 0xff000000

/* Register: RX_PAYLOAD_1 */
#define RX_PAYLOAD_1_OFFSET 0x80
#define RX_PAYLOAD_1_RESET 0x0

/* Field: PAYLOAD_BYTE_4 */
#define RX_PAYLOAD_1_PAYLOAD_BYTE_4_OFFSET 0
#define RX_PAYLOAD_1_PAYLOAD_BYTE_4_WIDTH 8
#define RX_PAYLOAD_1_PAYLOAD_BYTE_4_RESET 0x0
#define RX_PAYLOAD_1_PAYLOAD_BYTE_4_MASK 0xff

/* Field: PAYLOAD_BYTE_5 */
#define RX_PAYLOAD_1_PAYLOAD_BYTE_5_OFFSET 8
#define RX_PAYLOAD_1_PAYLOAD_BYTE_5_WIDTH 8
#define RX_PAYLOAD_1_PAYLOAD_BYTE_5_RESET 0x0
#define RX_PAYLOAD_1_PAYLOAD_BYTE_5_MASK 0xff00

/* Field: PAYLOAD_BYTE_6 */
#define RX_PAYLOAD_1_PAYLOAD_BYTE_6_OFFSET 16
#define RX_PAYLOAD_1_PAYLOAD_BYTE_6_WIDTH 8
#define RX_PAYLOAD_1_PAYLOAD_BYTE_6_RESET 0x0
#define RX_PAYLOAD_1_PAYLOAD_BYTE_6_MASK 0xff0000

/* Field: PAYLOAD_BYTE_7 */
#define RX_PAYLOAD_1_PAYLOAD_BYTE_7_OFFSET 24
#define RX_PAYLOAD_1_PAYLOAD_BYTE_7_WIDTH 8
#define RX_PAYLOAD_1_PAYLOAD_BYTE_7_RESET 0x0
#define RX_PAYLOAD_1_PAYLOAD_BYTE_7_MASK 0xff000000

#endif