class CANOLA_AXI_SLAVE_H:

    BASEADDR = 0x0

    """ Register: STATUS """
    STATUS_OFFSET = 0x0
    STATUS_RESET = 0x0

    """ Field: RX_MSG_VALID """
    STATUS_RX_MSG_VALID_OFFSET = 0
    STATUS_RX_MSG_VALID_WIDTH = 1
    STATUS_RX_MSG_VALID_RESET = 0x0
    STATUS_RX_MSG_VALID_MASK = 0x1

    """ Field: TX_BUSY """
    STATUS_TX_BUSY_OFFSET = 1
    STATUS_TX_BUSY_WIDTH = 1
    STATUS_TX_BUSY_RESET = 0x0
    STATUS_TX_BUSY_MASK = 0x2

    """ Field: TX_DONE """
    STATUS_TX_DONE_OFFSET = 2
    STATUS_TX_DONE_WIDTH = 1
    STATUS_TX_DONE_RESET = 0x0
    STATUS_TX_DONE_MASK = 0x4

    """ Field: TX_FAILED """
    STATUS_TX_FAILED_OFFSET = 3
    STATUS_TX_FAILED_WIDTH = 1
    STATUS_TX_FAILED_RESET = 0x0
    STATUS_TX_FAILED_MASK = 0x8

    """ Field: ERROR_STATE """
    STATUS_ERROR_STATE_OFFSET = 4
    STATUS_ERROR_STATE_WIDTH = 2
    STATUS_ERROR_STATE_RESET = 0x0
    STATUS_ERROR_STATE_MASK = 0x30

    """ Register: CONTROL """
    CONTROL_OFFSET = 0x4
    CONTROL_RESET = 0x0

    """ Field: TX_START """
    CONTROL_TX_START_OFFSET = 0
    CONTROL_TX_START_WIDTH = 1
    CONTROL_TX_START_RESET = 0x0
    CONTROL_TX_START_MASK = 0x1

    """ Register: CONFIG """
    CONFIG_OFFSET = 0x8
    CONFIG_RESET = 0x0

    """ Field: TX_RETRANSMIT_EN """
    CONFIG_TX_RETRANSMIT_EN_OFFSET = 0
    CONFIG_TX_RETRANSMIT_EN_WIDTH = 1
    CONFIG_TX_RETRANSMIT_EN_RESET = 0x0
    CONFIG_TX_RETRANSMIT_EN_MASK = 0x1

    """ Field: BTL_TRIPLE_SAMPLING_EN """
    CONFIG_BTL_TRIPLE_SAMPLING_EN_OFFSET = 1
    CONFIG_BTL_TRIPLE_SAMPLING_EN_WIDTH = 1
    CONFIG_BTL_TRIPLE_SAMPLING_EN_RESET = 0x0
    CONFIG_BTL_TRIPLE_SAMPLING_EN_MASK = 0x2

    """ Register: BTL_PROP_SEG """
    BTL_PROP_SEG_OFFSET = 0x20
    BTL_PROP_SEG_RESET = 0x7

    """ Register: BTL_PHASE_SEG1 """
    BTL_PHASE_SEG1_OFFSET = 0x24
    BTL_PHASE_SEG1_RESET = 0x7

    """ Register: BTL_PHASE_SEG2 """
    BTL_PHASE_SEG2_OFFSET = 0x28
    BTL_PHASE_SEG2_RESET = 0x7

    """ Register: BTL_SYNC_JUMP_WIDTH """
    BTL_SYNC_JUMP_WIDTH_OFFSET = 0x2c
    BTL_SYNC_JUMP_WIDTH_RESET = 0x1

    """ Register: BTL_TIME_QUANTA_CLOCK_SCALE """
    BTL_TIME_QUANTA_CLOCK_SCALE_OFFSET = 0x30
    BTL_TIME_QUANTA_CLOCK_SCALE_RESET = 0xF

    """ Register: TRANSMIT_ERROR_COUNT """
    TRANSMIT_ERROR_COUNT_OFFSET = 0x34
    TRANSMIT_ERROR_COUNT_RESET = 0x0

    """ Register: RECEIVE_ERROR_COUNT """
    RECEIVE_ERROR_COUNT_OFFSET = 0x38
    RECEIVE_ERROR_COUNT_RESET = 0x0

    """ Register: TX_MSG_SENT_COUNT """
    TX_MSG_SENT_COUNT_OFFSET = 0x3c
    TX_MSG_SENT_COUNT_RESET = 0x0

    """ Register: TX_ACK_ERROR_COUNT """
    TX_ACK_ERROR_COUNT_OFFSET = 0x40
    TX_ACK_ERROR_COUNT_RESET = 0x0

    """ Register: TX_ARB_LOST_COUNT """
    TX_ARB_LOST_COUNT_OFFSET = 0x44
    TX_ARB_LOST_COUNT_RESET = 0x0

    """ Register: TX_BIT_ERROR_COUNT """
    TX_BIT_ERROR_COUNT_OFFSET = 0x48
    TX_BIT_ERROR_COUNT_RESET = 0x0

    """ Register: TX_RETRANSMIT_COUNT """
    TX_RETRANSMIT_COUNT_OFFSET = 0x4c
    TX_RETRANSMIT_COUNT_RESET = 0x0

    """ Register: RX_MSG_RECV_COUNT """
    RX_MSG_RECV_COUNT_OFFSET = 0x50
    RX_MSG_RECV_COUNT_RESET = 0x0

    """ Register: RX_CRC_ERROR_COUNT """
    RX_CRC_ERROR_COUNT_OFFSET = 0x54
    RX_CRC_ERROR_COUNT_RESET = 0x0

    """ Register: RX_FORM_ERROR_COUNT """
    RX_FORM_ERROR_COUNT_OFFSET = 0x58
    RX_FORM_ERROR_COUNT_RESET = 0x0

    """ Register: RX_STUFF_ERROR_COUNT """
    RX_STUFF_ERROR_COUNT_OFFSET = 0x5c
    RX_STUFF_ERROR_COUNT_RESET = 0x0

    """ Register: TX_MSG_ID """
    TX_MSG_ID_OFFSET = 0x60
    TX_MSG_ID_RESET = 0x0

    """ Field: EXT_ID_EN """
    TX_MSG_ID_EXT_ID_EN_OFFSET = 0
    TX_MSG_ID_EXT_ID_EN_WIDTH = 1
    TX_MSG_ID_EXT_ID_EN_RESET = 0x0
    TX_MSG_ID_EXT_ID_EN_MASK = 0x1

    """ Field: RTR_EN """
    TX_MSG_ID_RTR_EN_OFFSET = 1
    TX_MSG_ID_RTR_EN_WIDTH = 1
    TX_MSG_ID_RTR_EN_RESET = 0x0
    TX_MSG_ID_RTR_EN_MASK = 0x2

    """ Field: ARB_ID_B """
    TX_MSG_ID_ARB_ID_B_OFFSET = 2
    TX_MSG_ID_ARB_ID_B_WIDTH = 18
    TX_MSG_ID_ARB_ID_B_RESET = 0x0
    TX_MSG_ID_ARB_ID_B_MASK = 0xffffc

    """ Field: ARB_ID_A """
    TX_MSG_ID_ARB_ID_A_OFFSET = 20
    TX_MSG_ID_ARB_ID_A_WIDTH = 11
    TX_MSG_ID_ARB_ID_A_RESET = 0x0
    TX_MSG_ID_ARB_ID_A_MASK = 0x7ff00000

    """ Register: TX_PAYLOAD_LENGTH """
    TX_PAYLOAD_LENGTH_OFFSET = 0x64
    TX_PAYLOAD_LENGTH_RESET = 0x0

    """ Register: TX_PAYLOAD_0 """
    TX_PAYLOAD_0_OFFSET = 0x68
    TX_PAYLOAD_0_RESET = 0x0

    """ Field: PAYLOAD_BYTE_0 """
    TX_PAYLOAD_0_PAYLOAD_BYTE_0_OFFSET = 0
    TX_PAYLOAD_0_PAYLOAD_BYTE_0_WIDTH = 8
    TX_PAYLOAD_0_PAYLOAD_BYTE_0_RESET = 0x0
    TX_PAYLOAD_0_PAYLOAD_BYTE_0_MASK = 0xff

    """ Field: PAYLOAD_BYTE_1 """
    TX_PAYLOAD_0_PAYLOAD_BYTE_1_OFFSET = 8
    TX_PAYLOAD_0_PAYLOAD_BYTE_1_WIDTH = 8
    TX_PAYLOAD_0_PAYLOAD_BYTE_1_RESET = 0x0
    TX_PAYLOAD_0_PAYLOAD_BYTE_1_MASK = 0xff00

    """ Field: PAYLOAD_BYTE_2 """
    TX_PAYLOAD_0_PAYLOAD_BYTE_2_OFFSET = 16
    TX_PAYLOAD_0_PAYLOAD_BYTE_2_WIDTH = 8
    TX_PAYLOAD_0_PAYLOAD_BYTE_2_RESET = 0x0
    TX_PAYLOAD_0_PAYLOAD_BYTE_2_MASK = 0xff0000

    """ Field: PAYLOAD_BYTE_3 """
    TX_PAYLOAD_0_PAYLOAD_BYTE_3_OFFSET = 24
    TX_PAYLOAD_0_PAYLOAD_BYTE_3_WIDTH = 8
    TX_PAYLOAD_0_PAYLOAD_BYTE_3_RESET = 0x0
    TX_PAYLOAD_0_PAYLOAD_BYTE_3_MASK = 0xff000000

    """ Register: TX_PAYLOAD_1 """
    TX_PAYLOAD_1_OFFSET = 0x6c
    TX_PAYLOAD_1_RESET = 0x0

    """ Field: PAYLOAD_BYTE_4 """
    TX_PAYLOAD_1_PAYLOAD_BYTE_4_OFFSET = 0
    TX_PAYLOAD_1_PAYLOAD_BYTE_4_WIDTH = 8
    TX_PAYLOAD_1_PAYLOAD_BYTE_4_RESET = 0x0
    TX_PAYLOAD_1_PAYLOAD_BYTE_4_MASK = 0xff

    """ Field: PAYLOAD_BYTE_5 """
    TX_PAYLOAD_1_PAYLOAD_BYTE_5_OFFSET = 8
    TX_PAYLOAD_1_PAYLOAD_BYTE_5_WIDTH = 8
    TX_PAYLOAD_1_PAYLOAD_BYTE_5_RESET = 0x0
    TX_PAYLOAD_1_PAYLOAD_BYTE_5_MASK = 0xff00

    """ Field: PAYLOAD_BYTE_6 """
    TX_PAYLOAD_1_PAYLOAD_BYTE_6_OFFSET = 16
    TX_PAYLOAD_1_PAYLOAD_BYTE_6_WIDTH = 8
    TX_PAYLOAD_1_PAYLOAD_BYTE_6_RESET = 0x0
    TX_PAYLOAD_1_PAYLOAD_BYTE_6_MASK = 0xff0000

    """ Field: PAYLOAD_BYTE_7 """
    TX_PAYLOAD_1_PAYLOAD_BYTE_7_OFFSET = 24
    TX_PAYLOAD_1_PAYLOAD_BYTE_7_WIDTH = 8
    TX_PAYLOAD_1_PAYLOAD_BYTE_7_RESET = 0x0
    TX_PAYLOAD_1_PAYLOAD_BYTE_7_MASK = 0xff000000

    """ Register: RX_MSG_ID """
    RX_MSG_ID_OFFSET = 0x70
    RX_MSG_ID_RESET = 0x0

    """ Field: EXT_ID_EN """
    RX_MSG_ID_EXT_ID_EN_OFFSET = 0
    RX_MSG_ID_EXT_ID_EN_WIDTH = 1
    RX_MSG_ID_EXT_ID_EN_RESET = 0x0
    RX_MSG_ID_EXT_ID_EN_MASK = 0x1

    """ Field: RTR_EN """
    RX_MSG_ID_RTR_EN_OFFSET = 1
    RX_MSG_ID_RTR_EN_WIDTH = 1
    RX_MSG_ID_RTR_EN_RESET = 0x0
    RX_MSG_ID_RTR_EN_MASK = 0x2

    """ Field: ARB_ID_B """
    RX_MSG_ID_ARB_ID_B_OFFSET = 2
    RX_MSG_ID_ARB_ID_B_WIDTH = 18
    RX_MSG_ID_ARB_ID_B_RESET = 0x0
    RX_MSG_ID_ARB_ID_B_MASK = 0xffffc

    """ Field: ARB_ID_A """
    RX_MSG_ID_ARB_ID_A_OFFSET = 20
    RX_MSG_ID_ARB_ID_A_WIDTH = 11
    RX_MSG_ID_ARB_ID_A_RESET = 0x0
    RX_MSG_ID_ARB_ID_A_MASK = 0x7ff00000

    """ Register: RX_PAYLOAD_LENGTH """
    RX_PAYLOAD_LENGTH_OFFSET = 0x74
    RX_PAYLOAD_LENGTH_RESET = 0x0

    """ Register: RX_PAYLOAD_0 """
    RX_PAYLOAD_0_OFFSET = 0x78
    RX_PAYLOAD_0_RESET = 0x0

    """ Field: PAYLOAD_BYTE_0 """
    RX_PAYLOAD_0_PAYLOAD_BYTE_0_OFFSET = 0
    RX_PAYLOAD_0_PAYLOAD_BYTE_0_WIDTH = 8
    RX_PAYLOAD_0_PAYLOAD_BYTE_0_RESET = 0x0
    RX_PAYLOAD_0_PAYLOAD_BYTE_0_MASK = 0xff

    """ Field: PAYLOAD_BYTE_1 """
    RX_PAYLOAD_0_PAYLOAD_BYTE_1_OFFSET = 8
    RX_PAYLOAD_0_PAYLOAD_BYTE_1_WIDTH = 8
    RX_PAYLOAD_0_PAYLOAD_BYTE_1_RESET = 0x0
    RX_PAYLOAD_0_PAYLOAD_BYTE_1_MASK = 0xff00

    """ Field: PAYLOAD_BYTE_2 """
    RX_PAYLOAD_0_PAYLOAD_BYTE_2_OFFSET = 16
    RX_PAYLOAD_0_PAYLOAD_BYTE_2_WIDTH = 8
    RX_PAYLOAD_0_PAYLOAD_BYTE_2_RESET = 0x0
    RX_PAYLOAD_0_PAYLOAD_BYTE_2_MASK = 0xff0000

    """ Field: PAYLOAD_BYTE_3 """
    RX_PAYLOAD_0_PAYLOAD_BYTE_3_OFFSET = 24
    RX_PAYLOAD_0_PAYLOAD_BYTE_3_WIDTH = 8
    RX_PAYLOAD_0_PAYLOAD_BYTE_3_RESET = 0x0
    RX_PAYLOAD_0_PAYLOAD_BYTE_3_MASK = 0xff000000

    """ Register: RX_PAYLOAD_1 """
    RX_PAYLOAD_1_OFFSET = 0x7c
    RX_PAYLOAD_1_RESET = 0x0

    """ Field: PAYLOAD_BYTE_4 """
    RX_PAYLOAD_1_PAYLOAD_BYTE_4_OFFSET = 0
    RX_PAYLOAD_1_PAYLOAD_BYTE_4_WIDTH = 8
    RX_PAYLOAD_1_PAYLOAD_BYTE_4_RESET = 0x0
    RX_PAYLOAD_1_PAYLOAD_BYTE_4_MASK = 0xff

    """ Field: PAYLOAD_BYTE_5 """
    RX_PAYLOAD_1_PAYLOAD_BYTE_5_OFFSET = 8
    RX_PAYLOAD_1_PAYLOAD_BYTE_5_WIDTH = 8
    RX_PAYLOAD_1_PAYLOAD_BYTE_5_RESET = 0x0
    RX_PAYLOAD_1_PAYLOAD_BYTE_5_MASK = 0xff00

    """ Field: PAYLOAD_BYTE_6 """
    RX_PAYLOAD_1_PAYLOAD_BYTE_6_OFFSET = 16
    RX_PAYLOAD_1_PAYLOAD_BYTE_6_WIDTH = 8
    RX_PAYLOAD_1_PAYLOAD_BYTE_6_RESET = 0x0
    RX_PAYLOAD_1_PAYLOAD_BYTE_6_MASK = 0xff0000

    """ Field: PAYLOAD_BYTE_7 """
    RX_PAYLOAD_1_PAYLOAD_BYTE_7_OFFSET = 24
    RX_PAYLOAD_1_PAYLOAD_BYTE_7_WIDTH = 8
    RX_PAYLOAD_1_PAYLOAD_BYTE_7_RESET = 0x0
    RX_PAYLOAD_1_PAYLOAD_BYTE_7_MASK = 0xff000000
